### ISSUE TITLE
Expanding Mode consequently changes orientation of other elements

### ISSUE THREAD

**Issue by starkfire** [starkfire/Caviar#1]
button.scss
```css
&.expanding{
	&:hover{
	        $exp: 1em*0.01;
		padding: { 
			top: $btn-big-vp+$exp; 
			right: $btn-big-hp+$exp; 
			bottom: $btn-big-vp+$exp; 
		left: $btn-big-hp+$exp; 
		}
	transition-duration: 0.3s;
}
	
```
